-- ================================================================
-- DYNAMIC SALES PLANNING - TEST QUERIES
-- Database: LANDING_CO.FLATFILES
-- Created: January 17, 2026
-- ================================================================

-- Set context
USE DATABASE LANDING_CO;
USE SCHEMA FLATFILES;

-- ================================================================
-- 1. BASIC DATA VALIDATION QUERIES
-- ================================================================

-- Test 1: Row counts for all tables
SELECT 'SALES_INVOICE' as TABLE_NAME, COUNT(*) as ROW_COUNT 
FROM DYNAMIC_PLANNING_SALES_INVOICE
UNION ALL
SELECT 'RETAILER' as TABLE_NAME, COUNT(*) as ROW_COUNT 
FROM DYNAMIC_PLANNING_RETAILER
UNION ALL
SELECT 'SALES_FORECAST' as TABLE_NAME, COUNT(*) as ROW_COUNT 
FROM DYNAMIC_PLANNING_SALES_FORECAST
UNION ALL
SELECT 'INVENTORY' as TABLE_NAME, COUNT(*) as ROW_COUNT 
FROM DYNAMIC_PLANNING_INVENTORY;

-- Test 2: View sample records from each table
SELECT * FROM DYNAMIC_PLANNING_SALES_INVOICE LIMIT 5;
SELECT * FROM DYNAMIC_PLANNING_RETAILER LIMIT 5;
SELECT * FROM DYNAMIC_PLANNING_SALES_FORECAST LIMIT 5;
SELECT * FROM DYNAMIC_PLANNING_INVENTORY LIMIT 5;

-- ================================================================
-- 2. SALES INVOICE ANALYSIS
-- ================================================================

-- Test 3: Total sales quantity by brand and category
SELECT 
    INV_BRAND,
    INV_CATEGORY,
    SUM(INV_QTY_EACHES) as TOTAL_QTY,
    SUM(INV_QTY_DZ_EACHES) as TOTAL_DZ
FROM DYNAMIC_PLANNING_SALES_INVOICE
GROUP BY INV_BRAND, INV_CATEGORY
ORDER BY TOTAL_QTY DESC;

-- Test 4: Sales by strategic account
SELECT 
    INV_STRATEGIC_ACCOUNT,
    COUNT(DISTINCT INV_FAMILY) as PRODUCT_FAMILIES,
    SUM(INV_QTY_EACHES) as TOTAL_UNITS_SOLD
FROM DYNAMIC_PLANNING_SALES_INVOICE
GROUP BY INV_STRATEGIC_ACCOUNT
ORDER BY TOTAL_UNITS_SOLD DESC;

-- Test 5: Monthly sales trend
SELECT 
    INV_YEAR,
    INV_MONTH,
    INV_CATEGORY,
    SUM(INV_QTY_EACHES) as MONTHLY_QTY
FROM DYNAMIC_PLANNING_SALES_INVOICE
GROUP BY INV_YEAR, INV_MONTH, INV_CATEGORY
ORDER BY INV_YEAR, INV_MONTH, INV_CATEGORY;

-- Test 6: Product class performance
SELECT 
    INV_PRODUCT_CLASS,
    INV_CATEGORY,
    COUNT(*) as ORDER_COUNT,
    SUM(INV_QTY_EACHES) as TOTAL_QTY
FROM DYNAMIC_PLANNING_SALES_INVOICE
GROUP BY INV_PRODUCT_CLASS, INV_CATEGORY
ORDER BY TOTAL_QTY DESC;

-- ================================================================
-- 3. RETAILER INVENTORY ANALYSIS
-- ================================================================

-- Test 7: Current inventory levels by retailer and product
SELECT 
    RETAILER,
    PRODUCT_MODEL,
    YEAR,
    MONTH_NAME,
    AVG(OH_INVENTORY) as AVG_ON_HAND,
    AVG(STOCK_RECEIPTS) as AVG_RECEIPTS
FROM DYNAMIC_PLANNING_RETAILER
GROUP BY RETAILER, PRODUCT_MODEL, YEAR, MONTH_NAME
ORDER BY RETAILER, PRODUCT_MODEL;

-- Test 8: Budget vs actual comparison
SELECT 
    RETAILER,
    PRODUCT_MODEL,
    MONTH_NAME,
    OH_INVENTORY as ACTUAL_OH,
    BUDGET_OH as BUDGET_OH,
    (OH_INVENTORY - BUDGET_OH) as VARIANCE,
    ROUND((OH_INVENTORY - BUDGET_OH) * 100.0 / NULLIF(BUDGET_OH, 0), 2) as VARIANCE_PCT
FROM DYNAMIC_PLANNING_RETAILER
WHERE BUDGET_OH > 0
ORDER BY ABS(OH_INVENTORY - BUDGET_OH) DESC;

-- Test 9: Weekly inventory trend for a specific product
SELECT 
    RETAILER,
    PRODUCT_MODEL,
    WEEK,
    WEEK_END_DATE,
    OH_INVENTORY,
    STOCK_RECEIPTS,
    COMP_SLS_ULY
FROM DYNAMIC_PLANNING_RETAILER
WHERE PRODUCT_MODEL = 'Paradym'
ORDER BY WEEK;

-- Test 10: Sell-through performance
SELECT 
    RETAILER,
    PRODUCT_MODEL,
    QUARTER,
    AVG(CAST(SELL_THRU_FC AS FLOAT)) as AVG_SELL_THRU_FORECAST,
    AVG(COMP_SLS_ULY) as AVG_COMP_SALES
FROM DYNAMIC_PLANNING_RETAILER
GROUP BY RETAILER, PRODUCT_MODEL, QUARTER
ORDER BY RETAILER, QUARTER;

-- ================================================================
-- 4. SALES FORECAST ANALYSIS
-- ================================================================

-- Test 11: Total forecast by category and month
SELECT 
    FCST_CATEGORY,
    FCST_MONTH,
    SUM(FCST_QTY) as TOTAL_FORECAST_QTY,
    SUM(FCST_REVENUE) as TOTAL_FORECAST_REVENUE,
    ROUND(SUM(FCST_REVENUE) / NULLIF(SUM(FCST_QTY), 0), 2) as AVG_PRICE
FROM DYNAMIC_PLANNING_SALES_FORECAST
GROUP BY FCST_CATEGORY, FCST_MONTH
ORDER BY FCST_MONTH, FCST_CATEGORY;

-- Test 12: Forecast by strategic account
SELECT 
    FCST_STRATEGIC_ACCOUNT,
    FCST_PROD_TYPE,
    COUNT(*) as FORECAST_LINES,
    SUM(FCST_QTY) as TOTAL_QTY,
    SUM(FCST_REVENUE) as TOTAL_REVENUE
FROM DYNAMIC_PLANNING_SALES_FORECAST
GROUP BY FCST_STRATEGIC_ACCOUNT, FCST_PROD_TYPE
ORDER BY TOTAL_REVENUE DESC;

-- Test 13: Product model forecast summary
SELECT 
    FCST_PROD_MODEL,
    FCST_CAT_FAMILY,
    MIN(FCST_MONTH) as FIRST_FORECAST_MONTH,
    MAX(FCST_MONTH) as LAST_FORECAST_MONTH,
    SUM(FCST_QTY) as TOTAL_FORECAST_QTY,
    SUM(FCST_REVENUE) as TOTAL_FORECAST_REVENUE
FROM DYNAMIC_PLANNING_SALES_FORECAST
GROUP BY FCST_PROD_MODEL, FCST_CAT_FAMILY
ORDER BY TOTAL_FORECAST_REVENUE DESC;

-- Test 14: Monthly forecast trend
SELECT 
    FCST_YEAR,
    FCST_MONTH,
    FCST_RPT_MONTH,
    SUM(FCST_QTY) as MONTHLY_FORECAST_QTY,
    SUM(FCST_REVENUE) as MONTHLY_FORECAST_REVENUE
FROM DYNAMIC_PLANNING_SALES_FORECAST
GROUP BY FCST_YEAR, FCST_MONTH, FCST_RPT_MONTH
ORDER BY FCST_YEAR, FCST_MONTH;

-- ================================================================
-- 5. INVENTORY TRACKING ANALYSIS
-- ================================================================

-- Test 15: Current inventory by product family
SELECT 
    INVT_CAT_FAMILY,
    INVT_PRODUCT_MODEL,
    INVT_STOCK,
    SUM(CAST(INVT_OH AS INTEGER)) as TOTAL_ON_HAND,
    SUM(CAST(INVT_LAST_WEEK AS INTEGER)) as TOTAL_LAST_WEEK,
    SUM(CAST(INVT_OH AS INTEGER)) - SUM(CAST(INVT_LAST_WEEK AS INTEGER)) as WOW_CHANGE
FROM DYNAMIC_PLANNING_INVENTORY
GROUP BY INVT_CAT_FAMILY, INVT_PRODUCT_MODEL, INVT_STOCK
ORDER BY INVT_CAT_FAMILY;

-- Test 16: Weekly inventory trend by product
SELECT 
    INVT_PRODUCT_MODEL,
    INVT_YEAR,
    INVT_MONTH_NAME,
    INV_WEEK,
    INVT_WEEKEND_DATE,
    CAST(INVT_OH AS INTEGER) as ON_HAND,
    CAST(INVT_LAST_WEEK AS INTEGER) as LAST_WEEK,
    CAST(INVT_OH AS INTEGER) - CAST(INVT_LAST_WEEK AS INTEGER) as WEEKLY_CHANGE
FROM DYNAMIC_PLANNING_INVENTORY
WHERE INVT_PRODUCT_MODEL = 'Paradym'
ORDER BY INVT_WEEKEND_DATE;

-- Test 17: Low stock alerts
SELECT 
    INVT_CAT_FAMILY,
    INVT_PRODUCT_MODEL,
    INVT_STOCK,
    INVT_MONTH_NAME,
    CAST(INVT_OH AS INTEGER) as ON_HAND_QTY
FROM DYNAMIC_PLANNING_INVENTORY
WHERE INVT_STOCK = 'Low Stock'
ORDER BY CAST(INVT_OH AS INTEGER);

-- Test 18: Inventory turnover analysis
SELECT 
    INVT_CAT_FAMILY,
    INVT_YEAR,
    INVT_MONTH_NUM,
    COUNT(DISTINCT INV_WEEK) as WEEKS_TRACKED,
    AVG(CAST(INVT_OH AS INTEGER)) as AVG_INVENTORY,
    MIN(CAST(INVT_OH AS INTEGER)) as MIN_INVENTORY,
    MAX(CAST(INVT_OH AS INTEGER)) as MAX_INVENTORY
FROM DYNAMIC_PLANNING_INVENTORY
GROUP BY INVT_CAT_FAMILY, INVT_YEAR, INVT_MONTH_NUM
ORDER BY INVT_YEAR, INVT_MONTH_NUM, INVT_CAT_FAMILY;

-- ================================================================
-- 6. CROSS-TABLE ANALYTICAL QUERIES
-- ================================================================

-- Test 19: Sales vs Forecast comparison (by product family)
SELECT 
    COALESCE(si.INV_CAT_FAMILY, sf.FCST_CAT_FAMILY) as PRODUCT_FAMILY,
    COALESCE(si.INV_MONTH, sf.FCST_MONTH) as MONTH,
    SUM(si.INV_QTY_EACHES) as ACTUAL_SALES_QTY,
    SUM(sf.FCST_QTY) as FORECAST_QTY,
    SUM(si.INV_QTY_EACHES) - SUM(sf.FCST_QTY) as VARIANCE_QTY
FROM DYNAMIC_PLANNING_SALES_INVOICE si
FULL OUTER JOIN DYNAMIC_PLANNING_SALES_FORECAST sf 
    ON si.INV_CAT_FAMILY = sf.FCST_CAT_FAMILY 
    AND si.INV_MONTH = sf.FCST_MONTH
GROUP BY COALESCE(si.INV_CAT_FAMILY, sf.FCST_CAT_FAMILY),
         COALESCE(si.INV_MONTH, sf.FCST_MONTH)
ORDER BY MONTH, PRODUCT_FAMILY;

-- Test 20: Inventory vs Sales correlation
SELECT 
    i.INVT_PRODUCT_MODEL,
    i.INVT_MONTH_NAME,
    AVG(CAST(i.INVT_OH AS INTEGER)) as AVG_INVENTORY,
    SUM(si.INV_QTY_EACHES) as TOTAL_SALES
FROM DYNAMIC_PLANNING_INVENTORY i
LEFT JOIN DYNAMIC_PLANNING_SALES_INVOICE si 
    ON i.INVT_MONTH_NUM = si.INV_MONTH 
    AND i.INVT_YEAR = si.INV_YEAR
GROUP BY i.INVT_PRODUCT_MODEL, i.INVT_MONTH_NAME
ORDER BY i.INVT_PRODUCT_MODEL;

-- Test 21: Retailer performance summary
SELECT 
    r.RETAILER,
    r.PRODUCT_MODEL,
    AVG(r.OH_INVENTORY) as AVG_ON_HAND,
    SUM(r.STOCK_RECEIPTS) as TOTAL_RECEIPTS,
    SUM(si.INV_QTY_EACHES) as TOTAL_SALES_QTY
FROM DYNAMIC_PLANNING_RETAILER r
LEFT JOIN DYNAMIC_PLANNING_SALES_INVOICE si 
    ON r.RETAILER = si.INV_STRATEGIC_ACCOUNT 
    AND r.MONTH_NUMBER = si.INV_MONTH
GROUP BY r.RETAILER, r.PRODUCT_MODEL
ORDER BY TOTAL_SALES_QTY DESC;

-- Test 22: Complete sales planning view
SELECT 
    si.INV_BRAND,
    si.INV_CATEGORY,
    si.INV_STRATEGIC_ACCOUNT as RETAILER,
    si.INV_MONTH,
    SUM(si.INV_QTY_EACHES) as ACTUAL_SALES,
    AVG(sf.FCST_QTY) as FORECAST_QTY,
    AVG(r.OH_INVENTORY) as AVG_INVENTORY,
    AVG(r.BUDGET_OH) as BUDGET_INVENTORY
FROM DYNAMIC_PLANNING_SALES_INVOICE si
LEFT JOIN DYNAMIC_PLANNING_SALES_FORECAST sf 
    ON si.INV_STRATEGIC_ACCOUNT = sf.FCST_STRATEGIC_ACCOUNT 
    AND si.INV_MONTH = sf.FCST_MONTH
LEFT JOIN DYNAMIC_PLANNING_RETAILER r 
    ON si.INV_STRATEGIC_ACCOUNT = r.RETAILER 
    AND si.INV_MONTH = r.MONTH_NUMBER
GROUP BY si.INV_BRAND, si.INV_CATEGORY, si.INV_STRATEGIC_ACCOUNT, si.INV_MONTH
ORDER BY si.INV_MONTH, ACTUAL_SALES DESC;

-- ================================================================
-- 7. DATA QUALITY CHECKS
-- ================================================================

-- Test 23: Check for null values in key fields
SELECT 
    'SALES_INVOICE' as TABLE_NAME,
    SUM(CASE WHEN INV_BRAND IS NULL THEN 1 ELSE 0 END) as NULL_BRAND,
    SUM(CASE WHEN INV_QTY_EACHES IS NULL THEN 1 ELSE 0 END) as NULL_QTY
FROM DYNAMIC_PLANNING_SALES_INVOICE
UNION ALL
SELECT 
    'RETAILER' as TABLE_NAME,
    SUM(CASE WHEN RETAILER IS NULL THEN 1 ELSE 0 END) as NULL_RETAILER,
    SUM(CASE WHEN OH_INVENTORY IS NULL THEN 1 ELSE 0 END) as NULL_INVENTORY
FROM DYNAMIC_PLANNING_RETAILER
UNION ALL
SELECT 
    'FORECAST' as TABLE_NAME,
    SUM(CASE WHEN FCST_CATEGORY IS NULL THEN 1 ELSE 0 END) as NULL_CATEGORY,
    SUM(CASE WHEN FCST_QTY IS NULL THEN 1 ELSE 0 END) as NULL_QTY
FROM DYNAMIC_PLANNING_SALES_FORECAST
UNION ALL
SELECT 
    'INVENTORY' as TABLE_NAME,
    SUM(CASE WHEN INVT_PRODUCT_MODEL IS NULL THEN 1 ELSE 0 END) as NULL_MODEL,
    SUM(CASE WHEN INVT_OH IS NULL THEN 1 ELSE 0 END) as NULL_OH
FROM DYNAMIC_PLANNING_INVENTORY;

-- Test 24: Check for duplicate records
SELECT 
    INV_STRATEGIC_ACCOUNT,
    INV_PRODUCT_TYPE,
    INV_YEAR,
    INV_MONTH,
    COUNT(*) as RECORD_COUNT
FROM DYNAMIC_PLANNING_SALES_INVOICE
GROUP BY INV_STRATEGIC_ACCOUNT, INV_PRODUCT_TYPE, INV_YEAR, INV_MONTH
HAVING COUNT(*) > 1;

-- Test 25: Date range validation
SELECT 
    'SALES_INVOICE' as TABLE_NAME,
    MIN(INV_YEAR) as MIN_YEAR,
    MAX(INV_YEAR) as MAX_YEAR,
    MIN(INV_MONTH) as MIN_MONTH,
    MAX(INV_MONTH) as MAX_MONTH
FROM DYNAMIC_PLANNING_SALES_INVOICE
UNION ALL
SELECT 
    'FORECAST' as TABLE_NAME,
    MIN(FCST_YEAR),
    MAX(FCST_YEAR),
    MIN(FCST_MONTH),
    MAX(FCST_MONTH)
FROM DYNAMIC_PLANNING_SALES_FORECAST
UNION ALL
SELECT 
    'INVENTORY' as TABLE_NAME,
    MIN(INVT_YEAR),
    MAX(INVT_YEAR),
    MIN(INVT_MONTH_NUM),
    MAX(INVT_MONTH_NUM)
FROM DYNAMIC_PLANNING_INVENTORY;

-- ================================================================
-- END OF TEST QUERIES
-- ================================================================
